Molecules/Planの作成
SakaueYae/Yae-frontend-basic-last-assignment pull request #7
Opened 2022-06-28 12:47 UTC by SakaueYae

## セルフチェック
- [o] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [o] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [o] 記述の重複はないか

リンク
https://62484493b9d8a3003a5ce6dd-wssvddcfob.chromatic.com/?path=/story/atoms-button--button

2022-06-30 15:12 UTC, minezaki-mutsuki reviewed
全体的にpadding値などがfigmaと違いますので作りながらfigmaと実装したものを見比べてみるといいかなと思います(検証ツールは積極的に使いましょう！)

2022-06-30 15:12 UTC, minezaki-mutsuki commented on src/components/molecules/plan/plan.html
> +<table class="table standard">
daytimeとstanderdでクラス名を分けずに両方tableにして、色の変更等はnth-childを使いましょう

2022-06-30 15:12 UTC, minezaki-mutsuki commented on src/components/molecules/plan/plan.html
> +<table class="table daytime">
tableタグで表としてつくるよりもulとliタグでリストとして作った方がやりやすいと思います

2022-07-09 06:25 UTC, Ravie403 requested changes

2022-07-09 06:25 UTC, Ravie403 commented on src/components/molecules/plan/plan.scss
> +                    color: $orange_bistre;
```suggestion

```
親要素で指定されているのでここの2行は不要です

2022-07-09 06:25 UTC, Ravie403 commented on src/components/molecules/plan/plan.scss
> +        li:nth-child(1){
（修正不要）
nth-child(1) = first-childなのですが
どちらでも大丈夫だと思います。

2022-07-09 07:56 UTC, MoAI522 approved these changes
LGTM

2022-07-09 12:26 UTC, merged